version: "3.4"

services:
  app:
    image: otus-hla-social-network:latest
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        BUILDTYPE: "development"
    environment:
      - DB_HOST=mysql
      - PORT=8080
      - DB_USER=localhost
      - DB=otus_social_network
      - DB_PASSWORD=password
      - LOG_LEVEL=trace
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=otus_social_network
      - MYSQL_USER=sn_admin
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
